theme: minima
---
title: Joe Biden = Cutie
date: 2021-03-30
---
author: Joe Biden User
email: your-JoeBiden@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Your mom even loves Joe Biden
# social links
twitter_username: JoeBiden # DO NOT include the @ character, or else the build will fail!
github_username:  JoeBiden # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
